sudo: required
language: bash
env:
  global:
  - IMAGE_NAME=gableroux/unity3d:2018.3.4f1
  - BUILD_NAME=piong
services:
- docker
before_install:
- chmod +x ./ci/before_script.sh
- chmod +x ./ci/test.sh
- chmod +x ./ci/build.sh
- chmod +x ./ci/docker_test.sh
- chmod +x ./ci/docker_build.sh
- openssl aes-256-cbc -K $encrypted_8437b75c5e74_key -iv $encrypted_8437b75c5e74_iv -in Unity_v2018.x.ulf.enc -out Unity_v2018.x.ulf -d
- export UNITY_LICENSE_CONTENT=`cat Unity_v2018.x.ulf`
- rm Unity_v2018.x.ulf
- docker pull $IMAGE_NAME
jobs:
  include:
  - stage: test
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=editmode
    addons:
      artifacts:
        target_paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=playmode
    addons:
      artifacts:
        target_paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: build
    if: branch = master
    env: BUILD_TARGET=StandaloneLinux64
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        target_paths:
        - "./Builds/"
  - stage: build
    if: branch = master
    env: BUILD_TARGET=StandaloneOSX
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        target_paths:
        - "./Builds/"
  - stage: build
    if: branch = master
    env: BUILD_TARGET=StandaloneWindows64
    script: "chmod +x ./ci/docker_build.sh &&./ci/docker_build.sh"
    addons:
      artifacts:
        target_paths:
        - "./Builds/"
  - stage: build
    if: branch = master
    env: BUILD_TARGET=WebGL
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        target_paths:
        - "./Builds/"